from typing import Protocol

from .types import LogEntry, LogServerState


class LogletStore(Protocol):
    node_id: str

    async def put(self, entry: LogEntry, known_tail: int = 0) -> None: ...

    async def repair(self, entry: LogEntry, known_tail: int = 0) -> None: ...

    async def get(self, segment_id: str, position: int, known_tail: int = 0) -> LogEntry | None: ...

    async def entries(
        self, segment_id: str, start: int = 0, limit: int = 100
    ) -> tuple[LogEntry, ...]: ...

    async def prefix_trim(self, segment_id: str, trim_position: int) -> int: ...

    async def seal(self, segment_id: str, known_tail: int = 0) -> None: ...

    async def state(self, segment_id: str, known_tail: int = 0) -> LogServerState: ...

    async def segment_states(self) -> tuple[LogServerState, ...]: ...
